### ISSUE TITLE
No longer grabbing highest quality since latest update

### ISSUE THREAD

**Issue by SigismundDijkstra** [StigNygaard/Stigs_Art_Grabr#2]
Since the update that fixed iTunes it only seems to be grabbing low resolution images. On iTunes it only grabs 500x500 (URL should be 99999x99999 to automatically fetch the highest quality) but it's also occurring on other sites. Soundcloud for example is only fetching 200x200 images now.

**Comment by StigNygaard** [comment]
Hi @SigismundDijkstra 

Thanks for feedback.

**iTunes / Apple Music:**
Are you sure you have the latest version? I [just updated Art Grabr yesterday](https://github.com/StigNygaard/Stigs_Art_Grabr/issues/1) to support the new Apple site. With version 2020.04.25.0 it should work again? If not, it might be because of local differences of the site. What country-version of the site are you using?

**SoundCloud:**
I haven't used Art Grabr myself in a long period, so it is easily possibly support for SoundCloud or other sites have become broken after site-updates. But I just tried finding big artwork on a couple of SoundCloud pages, and it worked fine for me. Can you point me to a page where it doesn't work?

It is also possible that one of the changes I made yesterday also had positive effect on SoundCloud...

**Comment by SigismundDijkstra** [comment]
Sorry, I should have mentioned browser. I'm using Firefox 75 with Tampermonkey.

I have the latest version. I downgraded to the previous version and it's now correctly grabbing the high-res artwork on Soundcloud. I also tested Qobuz and it's the same so it seems to be happening everywhere. 

**Example:** https://www.qobuz.com/gb-en/album/lover-taylor-swift/cp53xl651si5a
**Latest version grabs:** https://static.qobuz.com/images/covers/5a/si/cp53xl651si5a_600.jpg
**v2019.11.03.0 grabs:** https://static.qobuz.com/images/covers/5a/si/cp53xl651si5a_max.jpg

**Comment by StigNygaard** [comment]
Strange. I have tested successfully, including now your qobuz.com link above, with Firefox75+Greasemonkey and Chrome81+Tampermonkey. Not with your combination, but seems unlikely that should make the difference.

Hmmm... Could I get you to look too see if some javascript error occurs when executing Art Grabr?

You can do it like this:

![image](https://user-images.githubusercontent.com/5936108/80315043-88cb8d00-87f5-11ea-9d40-da51f5e5bbcf.png)

1) Go to a page like above qobuz page.
2) Press F12. This should open Firefox' "developer tools".
3) Choose the "Console"-tab in developer tools (see above screenshot)
4) Click the Garbagebin icon below the tabs-row to clear any existing content in the console log.
5) Make sure at least the "Errors" button is selected (the button is dark)
6) Execute Art Grabr trying to find that big cover-art

Does it write anything in the Console log when executing Art Grabr?

**Comment by SigismundDijkstra** [comment]
No errors. I tested with Greasemonkey and have the same problem, disabled all other addons and userscripts but it persists. <.<

**Comment by StigNygaard** [comment]
It works for you with Chrome+Tampermonkey?!
Hmm, so somehow it doesn't like your Firefox even though you tried Firefox combined with both Greasemonkey and Tampermonkey - and disabled all other addons+userscripts? Really weird...

Is there anything special about your PC? Very small screen? Touch screen?
When using Firefox do you see the (first yellow then) red image-borders around the images it tries to update?
On a page like f.ex. https://www.last.fm/music/Fiona+Apple/+albums do you get the "20 images requested. Continue?" prompt when running Grabr in Firefox?

**Comment by SigismundDijkstra** [comment]
Windows 10, latest version. I do get the 20 images requested prompt.

I think I've figured it out though with the hovering. If I wait a moment before clicking it will fetch the high res image (once the image fully loads I guess), but if I click instantly it opens the low res image.

The previous version automatically redirects me to the high res image even if it hasn't loaded.

So it is actually working, I just have to  be patient and wait for the images to load now before clicking.

**Comment by StigNygaard** [comment]
@SigismundDijkstra I did change some things in latest release on how it handles the replacement of images, so it is definitely possible that a little more patience is required. I'm glad we found out what is happening, because for me it was really starting to sound mysterious :-)

I think I will close this issue and call it expected or accepted behaviour. There was some changes in the image-replacement method I had to make in Grabr to make iTunes working again.

Later I might try to get the image-replacement to work faster, but not sure I will be able to optimize it much.
